name: Build Artifact
on: 
  workflow_call:

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.19"      
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build
        runs: uv build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
