name: Tag a Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of Release"
        required: true
        type: choice
        options:
          - stable
          - dev

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
      sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.19"      
      - name: check out repo
        uses: actions/checkout@v4
      - name: get current version
        run: |
          REPO_VERSION=$(uv version --short)
          echo "REPO_VERSION=${REPO_VERSION}" >> "$GITHUB_ENV"
      - name: Check for dev version
        run: |
          echo ${{ env.REPO_VERSION }}          
          if [[ "${{ env.REPO_VERSION }}" =~ ^[0-9]*\.[0-9]*\.[0-9]*$ ]]; then echo "This seems like an already released version"; false; else echo "looking good"; true; fi
      - name: set git credentials
        run: |
          git config --global user.name "Forgejo Action CI"
          git config --global user.email "git@git.k-fortytwo.de"
      - name: Bump to stable
        if: ${{ inputs.type == 'stable' }}
        run: |
          uv version --bump stable
          git add pyproject.toml
          git commit -m "Update to stable version: $(uv version --short)"
          git push
      - name: sha
        id: sha
        run: echo "SHA=$(git log -1 --format=%H)" >> $GITHUB_OUTPUT}
      - name: get current version
        id: get-version
        run: |
          VERSION=$(uv version --short | sed 's/\.dev/-dev/')
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: print outputs
        run: |
          echo "tag: ${{ steps.get-version.outputs.VERSION }}"
          echo "sha: ${{ steps.sha.outputs.sha }}"
      #   run: git tag v${{ env.VERSION }}
      # - name: Push tag
      #   run: |
      #     git push
      #     git push -f --tags

  build-artifact:
    uses: ./.forgejo/workflows/build-artifact.yml

  build-docker:
    needs: update-version
    uses: ./.forgejo/workflows/build-docker.yml
    secrets:
      DOCKER_TESTREPO: ${{ secrets.DOCKER_TESTREPO }} 
      GH_TESTREPO: ${{ secrets.GH_TESTREPO }}
    with:
      type: ${{ inputs.type }}
      version: ${{ needs.update-version.outputs.version }}

          
  make_release:
    needs: [update-version, build-artifact, build-docker]
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: |
            echo "TAG=v${{ needs.update-version.outputs.version }}" >> $GITHUB_OUTPUT
      - name: Check for stable version
        id: stable
        run: |
            echo "STABLE=${{ inputs.type != 'stable' }}" >> $GITHUB_OUTPUT
      - name: Print version
        run: |
          echo "Version: ${{ steps.tag.outputs.tag }}"
          echo "Stable: ${{ steps.stable.outputs.stable }}"
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: actions/forgejo-release@v2.12.1
        with:
          direction: upload
          release-notes-assistant: true
          tag: ${{ steps.tag.outputs.tag }}
          sha: ${{ needs.update-version.outputs.sha }}
          release-dir: dist
          prerelease: ${{ steps.stable.outputs.stable }}
  
  bump_to_dev:
    needs: [make_release]
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.19"      
      - name: check out repo
        uses: actions/checkout@v4
      - name: set git credentials
        run: |
          git config --global user.name "Forgejo Action CI"
          git config --global user.email "git@git.k-fortytwo.de"
      - name: Bump to dev
        run: |
          git pull origin main
          uv version --bump patch --bump dev
          git add pyproject.toml
          git commit -m "Update to dev version: $(uv version --short)"
      - name: push
        run: git push



