name: Tag a Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of Release"
        required: true
        type: choice
        options:
          - stable
          - dev

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.19"      
      - name: check out repo
        uses: actions/checkout@v4
      - name: get current version
        run: |
          REPO_VERSION=$(uv version --short)
          echo "REPO_VERSION=${REPO_VERSION}" >> "$GITHUB_ENV"
      - name: Check for dev version
        run: |
          echo ${{ env.REPO_VERSION }}          
          if [[ "${{ env.REPO_VERSION }}" =~ ^[0-9]*\.[0-9]*\.[0-9]*$ ]]; then echo "This seems like an already released version"; false; else echo "looking good"; true; fi
      - name: set git credentials
        run: |
          git config --global user.name "Forgejo Action CI"
          git config --global user.email "git@git.k-fortytwo.de"
      - name: Bump to stable
        if: ${{ inputs.type == 'stable' }}
        run: |
          uv version --bump stable
          git add pyproject.toml
          git commit -m "Update to stable version: $(uv version --short)"
      - name: get current version
        run: |
          VERSION=$(uv version --short | sed 's/\.dev/-dev/')
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
      - name: Add tag
        run: git tag v${{ env.VERSION }}
      - name: Push tag
        run: |
          git push
          git push -f --tags
