name: Execute-remote

on:
  workflow_dispatch:

jobs:
  execute-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GH_TESTREPO }}
          repository: christofsteel/testrepo
          event-type: test-event
