name: Execute-remote

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.GH_TESTREPO }}
  REPO: christofsteel/testrepo

jobs:
  execute-remote:
    runs-on: ubuntu-latest
    steps:
      - name: manual trigger
        run: | 
          curl -X POST \
              -H "Authorization: token ${{ env.TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ env.REPO }}/dispatches \
              -d '{"event_type": "test-event"}'
