name: Test stuff

# Controls when the workflow will run
on:
  # Triggers the workflow on push with version tag
  push:
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: christofsteel/syng

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Print event trigger
        run: echo ${{ github.event_name }}
      - name: check out repo
        uses: actions/checkout@v4
      - name: Get best tag
        id: tagname
        run: |
          SHA="\"${IMAGE_NAME}:commit-$(git rev-parse --short HEAD)\""
          TAGS="${SHA}"
          case ${{ github.event_name }} in
          push)
          TAGS="$(git tag | sed 's/v\([^\.]\).\([^\.]\).\([^\.]\)/"${IMAGE_NAME}:\1", "${IMAGE_NAME}:\1.\2", "${IMAGE_NAME}:\1.\2.\3", "${IMAGE_NAME}:latest", ${SHA}/')"}
            ;;
          pull_request)
          TAGS="\"${IMAGE_NAME}:pr-${{ github.event.pull_request.head.ref }}\", {SHA}"
            ;;
          esac
          echo "TAGS=\"[${TAGS}]\"" >> "$GITHUB_OUTPUT"
      - name: Print tags
        run: echo ${{ steps.tagname.outputs.tags }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          endpoint: tcp://forgejo-dind:2375
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ steps.tagname.outputs.tags }}
