name: MyWorkflow

on:
  repository_dispatch:
    types: [test-event]

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: get repo
        run: |
          git clone https://git.k-fortytwo.de/christofsteel/syng-deploytest
          git checkout ${{ github.event.client_payload.sha }}
      - run: ls
